apiVersion: v1
kind: Namespace
metadata:
  name: logomotive
---
apiVersion: v1
kind: Service
metadata:
  name: logomotive-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: logomotive-app
  selector:
    service: logomotive-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logomotive
spec:
  replicas: 1
  selector:
    matchLabels:
      service: logomotive-svc
  template:
    metadata:
      labels:
        service: logomotive-svc
    spec:
      restartPolicy: Always
      containers:
      - name: logomotive
        image: arnemolland/logomotive
        imagePullPolicy: Always
        env:
        - name: MONGO_HOST
          value: mongo-svc
        - name: PORT
          value: "50051"
        ports:
        - name: logomotive-app
          containerPort: 50051
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi