default_platform(:mac)

def packages_get
  sh("cd .. && flutter packages get")
end

def flutter_build
  sh("cd .. && flutter build macos")
end

platform :mac do
  desc "Builds and notarizes a Developer ID app"
  lane :build do
    if is_ci
      setup_ci
    end
    packages_get
    sync_code_signing(
      type: "developer_id",
      readonly: is_ci,
      keychain_name: "action_keychain",
      keychain_password: ENV["FASTLANE_PASSWORD"],
    )
    flutter_build
    gym
    notarize(package: "./build/Logomotive.app")
  end

  lane :setup do
    setup_project
  end
  
  lane :setup_project do
    create_keychain(
      name: "action_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end
end
