apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $IMAGE
spec:    
  template:
    spec:
      serviceAccountName: gh-actions@molland.iam.gserviceaccount.com
      containers:
        image: gcr.io/$PROJECT_ID/$IMAGE:$RELEASE_VERSION
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        env:
        - name: PROJECT_ID
          value: $PROJECT_ID
        - name: MONGO_URI
          value: $MONGO_URI